### PR TITLE
Service for Dock, Undock and DockingState

### PR DESCRIPTION
**Pull request by nicofilliol**
In this pull request, the open pull request #58 is slightly modified to follow the style of `spot_wrapper.py` more closely and a service is added to get the current docking state of the robot. Also includes the fix proposed in #70 to solve issue #54, to prevent the interruption of the dock/undock commands.

### CODE REVIEW

**Comment by EricVoll** [comment]
Just noting that we've been running this code for quite some time now very reliably.

**Review by EricVoll — APPROVED** [review]
@heuristicus if you have any feedback to this PR, I'm happy to invest the time to implement it. Would be great if we could merge this PR though, now that you have control of the repo.

**Comment by heuristicus** [comment]
I was hoping to test this and managed to get hold of a dock, but our robot doesn't actually have docking capabilities so couldn't confirm that it's functional. In terms of additions the only thing I think would be good is to add an actionserver to do the same things - it's often more convenient that way rather than as a service, although it's good to have both.

**Comment by heuristicus** [comment]
Merged the changes to the main branch to here, probably needs to be tested again to make sure everything still works.

**Comment by heuristicus** [comment]
Going ahead and merging this. If problems are reported we can look at them then.

**Pull request merged**
