### PR TITLE
Add trajectory cmd

### PR DESCRIPTION
**Pull request by sktometometo**
- add /spot/trajectory service to issue a trajectory command which enables to move spot to a desired position.

### CODE REVIEW

**Comment by EricVoll** [comment]
Hi @sktometometo,
I have two questions:
1. Wouldn't it make more sense to have the trajectory cmd be a subscribed topic rather than a service? That would be more in line with the velocity and pose commands, which are also subscribed topics. (continuity)
<s>2. Why did you rename '_last_motion_command ' to ' _last_velocity_command'?</s> [Understood - Motion would not be clear since the velocity commands are also motions]

I'll test this branch on our spot in the next few days 😊

**Comment by sktometometo** [comment]
Hi @EricVoll.

Your idea sounds good. but I think there are 3 candidates of API for trajectory cmd including your suggestion and my implementation.
- topic ( e.g. /cmd_vel )
- service ( e.g. my implementation )
- action ( e.g. [Action API of move_base](http://wiki.ros.org/move_base#Action_API) )

There are [patterns](http://wiki.ros.org/ROS/Patterns/Communication) for ROS Communication API.
I implemented trajectory cmd as a service because I thought it is a kind of remote procedure which issue a [robot command](https://dev.bostondynamics.com/docs/concepts/robot_services#robot-command) with Boston Dynamics API.
But it is also good to make trajectory cmd as a topic or an action if treating trajectory cmd as a 'continuous data stream' like /cmd_vel or a 'discrete behavior' like move_base.
That is why I leave this PR as draft.

I think it is good to discuss this issue more.

**Comment by dniewinski** [comment]
I think actions are the most correct here.  This is similar functionality to move_base

**Comment by heuristicus** [comment]
Hi, thanks for this PR - it works well but as @dniewinski suggested I think it would work better as an action since then it is possible to call it from elsewhere and know that the action has completed.

I've done a bit of work at https://github.com/ori-drs/spot_ros/commit/ee594aa14a5eaf7d40a4bfe3217131f64cd025cf to convert the service into an actionserver. I could make a PR into @sktometometo's branch if it would be useful to add into this PR. If you have any suggestions for improvements they are most welcome.

**Comment by EricVoll** [comment]
I'm happy to test your branch this week and will give you some feedback if I notice anything :)

**Comment by sktometometo** [comment]
hi @heuristicus , thank you for your work of action server implementation!

I also think action server is better than service for this case, and I am planning to use your version.
So could you make a PR with your patch, or can I make a PR with your patch? (I have already make a branch with this branch, your patch, + suttle changes and rebased on origin/master https://github.com/sktometometo/spot_ros/pull/2 ).

**Comment by heuristicus** [comment]
Hi @sktometometo, thanks for your initial efforts on this, you added a lot of useful things. I think since you've already made a branch it would make sense for you to make the PR with that branch.

**Comment by sktometometo** [comment]
@heuristicus thank you for your kind reply!. I have made PR with you patch

**Pull request closed without merging**
