### PR TITLE
Add service call to set maximum velocity, use synchro trajectory command

### PR DESCRIPTION
**Pull request by heuristicus**
The service call `/spot/max_velocity` receives a twist message and sets the mobility params vel_lim max_vel to the linear x and y, and angular z values in the message. This velocity limit affects anything that moves the robot around, such as the trajectory command and velocity command. The service call adds a srv to spot_msgs.

Output exception string when power_on command fails - I had a few times where the power_on command failed but I didn't receive any useful feedback from the service.

Fix minor typo in behavior_fault function name

Populate state_description in the estop state message

Minor cosmetic changes to srv imports and some comments for readability

Previously a plain `trajectory_command` was being used to run trajectory commands. On 2.3.5 I had trouble getting this to work for some reason. When the robot received a command it would move very slightly and then do nothing. Changing to use `synchro_se2_trajectory_point_command` returned it to the expected behaviour. This also puts it in line with the other motion commands.

I have tested the maximum velocity service with the trajectory controller and it works well.

### CODE REVIEW

**Comment by heuristicus** [comment]
If my rviz user interface is merged (https://github.com/clearpathrobotics/spot_ros/pull/44), should add the commits from https://github.com/ori-drs/spot_ros/tree/rviz-plugin-with-velocities to this branch so that velocities can be set from the UI.

**Comment by MarioGini** [comment]
I can confirm the issue using a `trajectory_command` that is resolved by using `synchro_se2_trajectory_point_command`, would be nice to see that being merged!

**Comment by civerachb-cpr** [comment]
Sorry about the delay getting to this!  The developer who previously maintained this project has moved on to other things.  I'm taking over, but I haven't had an opportunity to test these changes on our development robot as a final check before merging yet.
Thank-you all for your patience!

**Comment by civerachb-cpr** [comment]
I just merged your rviz update; can you please apply the changes you mentioned to add the velocity support to that and then I'll get this PR merged in as well.

**Comment by heuristicus** [comment]
Thank you for merging my other pull requests. I've merged the rviz velocity support into this branch. It looks like

Screenshot from 2021-08-11 08-24-15

I chose the limits on the values of the body pose and velocity mostly based on observations. I'm not sure the limits are actually necessary given that the API checks these things internally, but I thought an extra layer to make sure we got sensible values was a good idea. Of course, if not using the rviz tool those limits can be bypassed...

**Comment by civerachb-cpr** [comment]
Thanks for this!  I'll be testing it out on our office Spot later today, and assuming it all goes well it should be merged by EOD today.

**Pull request merged**
