### PR TITLE
adding pick service

### PR DESCRIPTION
**Pull request by mfheinemann**
Adding ROS service for PickObject Proto

### CODE REVIEW

**Comment by jeremysee2** [comment]
Have you tested that this works with the robot, e.g. executed the code and recorded a video of it?

**Comment by mfheinemann** [comment]
@jeremysee2 yeah, I tested it on spot. Here you see a "pick & place" but the PR only deals with the picking.

https://user-images.githubusercontent.com/97460777/223214283-07fe0e18-d69a-4134-9ff4-2eab36bb756d.mp4

**Comment by jeremysee2** [comment]
Just one question, I noticed you removed the unstow command in `force_trajectory`, does the pick service work if you start from the Stow position?

If it doesn't work maybe we should throw an exception when starting from that pose.

**Comment by mfheinemann** [comment]
Yeah, it works this way. If you look at the video, the arm directly goes to "look at ground" as part of grasp3d without being unstowed before.

**Comment by jeremysee2** [comment]
Then the PR is fine by me, @heuristicus any thoughts?

Also, you might want to run a Black formatter like this one for [VS Code](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) to pass the CI check.

**Comment by heuristicus** [comment]
Fine to merge once black has been applied. If you have black installed, just run `black .` in this repo.

**Comment by jeremysee2** [comment]
I've run this on my Spot, it seems to work as expected, to add another testing data point.

**Pull request merged**
