### PR TITLE
Update graphnav ROS Interface

### PR DESCRIPTION
**Pull request by sktometometo**
Update graphnav interface.

~~Since this PR is based on our fork which split from clearpath's master branch many months ago, Rebasing is still not fully done.~~

# Features

## Update `navigate_to` action interface

- Add cancel interface of navigate_to action

This enables to cancel action while executing `navigate_to`

- Split UploadGraph, SetLocalization services from navigate_to action
  + `~/upload_graph` (spot_msgs/UploadGraph)
  + `~/set_locallization_fiducial` (spot_msgs/SetLocalizationFiducial)
  + `~/set_localization_wapoint` (spot_msgs/SetLocalizationWaypoint)

This enables to execute navigate_to action without re-upload and localization after executing another navigate_to action

- Update `upload_graph` service to reduce uploading time

This PR enables that the service upload only no cached waypoints and edges.

## Add recording interfaces

- Add recording services below
  + `~/start_recording` (std_srvs/Trigger)
  + `~/stop_recording` (std_srvs/Trigger)
  + `~/download_graph` (spot_msgs/DownloadGraph)
  + `~/clear_graph` (spot_msgs/Trigger)

# Usage

## NavigateTo action interface

First, please upload graphnav map. (assuming that your map directory will be put as `/home/spot/test.walk`)
graphnav map can be created with android app.

```
rosservice call /spot/upload_graph "upload_filepath: '/home/spot/test.walk'" 
```

If correctly uploaded, you can see node list of your graphnav map with `list_graph`

```
rosservice call /spot/list_graph
```

And pleaes localize spot. In this case, it is assumed your robot can see an apriltag marker used in your graphnav map.

```
rosservice call /spot/set_localization_fiducial "{}"
```

Now you can call `navigate_to` action. ( Replace <node id>)

```
rostopic pub -1 /spot/navigate_to/goal spot_msgs/NavigateToActionGoal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
goal_id:
  stamp:
    secs: 0
    nsecs: 0
  id: ''
goal:
  id_navigate_to: '<node id>'" 
```

## Recording interface

If you want to start a new graph, please call `clear_graph` service.

```
rosservice call /spot/clear_graph "{}"
```

After that, please move Spot where it can see an ArpilTag. Now you can start recording.

```
rosservice call /spot/start_recording "{}"
```

and move Spot with teleop, after that, please call `stop_recording`

```
rosservice call /spot/stop_recording "{}"
```

Now spot can move with navigate_to command. if you want to see node id, please call `list_graph`

```
rosservice call /spot/list_graph "{}"
```

And in order to download graph from robot, please call `/spot/download_graph`

```
rosservice call /spot/download_graph "download_filepath: '/home/spot/test.walk'"
```

This will download graph and snapshots files to `/home/spot/test.walk`
You can use this graph to upload to robot, execute autowalk with tablet or visualize map with [Graphnav Map Viewer](https://github.com/boston-dynamics/spot-sdk/tree/master/python/examples/graph_nav_view_map)

### CODE REVIEW

**Comment by heuristicus** [comment]
@sktometometo I have not had any experience using graph nav components, but I noticed that boston dynamics made quite a few improvements to the system in the 3.0 release: https://support.bostondynamics.com/s/article/Spot-v3-0-Release-Notes. Since it was only released a few days ago I'm guessing you haven't had time to investigate the changes, but it might be worth checking compatibility with the 3.0 release as well before merging.

**Comment by sktometometo** [comment]
@heuristicus Thank you for comment. I will update one of our spots to 3.0 and check if this PR works.

**Comment by civerachb-cpr** [comment]
I'm also planning on updating our Spot to 3.0 for evaluation in the next few weeks so I'll double-check everything on our end before merging, too.

**Comment by sktometometo** [comment]
We confirmed that this branch works well with our robots ( with version 2.3.4 and 3.0.0 )

**Comment by civerachb-cpr** [comment]
Glad to hear it's working with both version!
I just got back from vacation and am catching up on things.  I'll do my best to test this out ASAP.  Thanks for your continued patience!

**Pull request closed without merging**
