### PR TITLE
WIP ROS2 Foxy branch

### PR DESCRIPTION
**Pull request by AustinDeric**
This PR shouldn't be merged, but instead should be the `foxy` branch.

# Changes
* Convert codebase to ros2 foxy
* Add CI: https://github.com/AustinDeric/spot_ros/actions/runs/274791604

# WIP pending
* python script conversion to ros2
* launch file conversion
* testing (manual, no automated test are planned in this PR)

### CODE REVIEW

**Comment by dniewinski** [comment]
Hi @AustinDeric .  Is this still a WIP?

**Comment by AustinDeric** [comment]
> Hi @AustinDeric . Is this still a WIP?

HI :wave: yes it is still WIP, not much left, i have some uncommitted changes locally that i will push up.  I am not sure if y'all want to merge this into master or make a new foxy branch.

**Comment by dniewinski** [comment]
Probably a foxy branch would be best.  Keeping ros 1 and 2 apart might be less confusing

**Comment by Raphtor** [comment]
What's the status on this?

**Comment by METEORITENMAX** [comment]
hi,
since there is no active development i started a package to port the driver to ROS 2.
The services: power_on, claim, stand, sit are working and it is possible to control the spot via the cmd_vel topic. I am planning to completely port the ros1 driver.

I somehow missed that PR when i started to port the driver. I also missed to create a fork..
If you interested we can merge this into your repo, but i am not sure how to proceed. Should I create another Draft PR?

Here is the link to our ROS 2 spot driver: https://github.com/MASKOR/spot_ros2

**Comment by heuristicus** [comment]
Closing this. People who want a ros2 driver should use https://github.com/bdaiinstitute/spot_ros2 for the time being. I hope that it will be possible to merge the work done there and here into one repository, see https://github.com/bdaiinstitute/spot_ros2/issues/25.

**Pull request closed without merging**
