### PR TITLE
Add trajectory command interface

### PR DESCRIPTION
**Pull request by sktometometo**
This PR is based on https://github.com/clearpathrobotics/spot_ros/pull/13 and includes action server implementation of https://github.com/ori-drs/spot_ros/commit/ee594aa14a5eaf7d40a4bfe3217131f64cd025cf by @heuristicus.

I added some changes to it
- rebase origin/master and resolve conflicts.
- allow STATUS_NEAR_GOAL to be recognized as at_goal status.

### CODE REVIEW

**Comment by heuristicus** [comment]
Thanks for including my changes. I tested them on our robot and was happy with the results.

For my own notes, `STATUS_NEAR_GOAL` details are at https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference.html?highlight=status_near_goal.

**Comment by tongtybj** [comment]
@dniewinski 

We have tested on this PR with our spot for round one month, and we are happy with the result of this new feature.
Please consider to merge this PR, if you think OK.

**Comment by tongtybj** [comment]
@dniewinski 

ping

**Comment by rgariepy** [comment]
Hey @tongtybj @heuristicus @sktometometo etc, sorry about the delay here, @dniewinski is on vacation. He's back early May, but I'll see if I can get someone else on this sooner!

**Comment by rgariepy** [comment]
Hey all, I conferred with @jhiggins-cpr and we'd like to wait until early next week when @dniewinski returns to merge this. We've had some problems with the ROS driver not working properly with the latest version of the Spot firmware and want to confirm that's resolved before we pull more changes into master.

**Pull request merged**
